// clang-format off

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/****************************************************************************
 Copyright (c) 2022-2023 Xiamen Yaji Software Co., Ltd.

 http://www.cocos.com

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
****************************************************************************/

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#elif defined(__GNUC__) || defined(__GNUG__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#elif defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable : 4101)
#endif


#define SWIG_STD_MOVE(OBJ) std::move(OBJ)


#include <stdio.h>


#include "bindings/jswrapper/SeApi.h"
#include "bindings/manual/jsb_conversions.h"
#include "bindings/manual/jsb_global.h"


#include "bindings/auto/3.7.x/jsb_native_remote_config_auto.h"
// Add more includes in the generated source file bellow
// ...



se::Class* __jsb_remoteconfig_FirebaseRemoteConfig_class = nullptr;
se::Object* __jsb_remoteconfig_FirebaseRemoteConfig_proto = nullptr;
SE_DECLARE_FINALIZE_FUNC(js_delete_remoteconfig_FirebaseRemoteConfig) 

static bool js_remoteconfig_FirebaseRemoteConfig_fetch(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    remoteconfig::FirebaseRemoteConfig *arg1 = (remoteconfig::FirebaseRemoteConfig *) NULL ;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<remoteconfig::FirebaseRemoteConfig>(s);
    if (nullptr == arg1) return true;
    (arg1)->fetch();
    
    
    return true;
}
SE_BIND_FUNC(js_remoteconfig_FirebaseRemoteConfig_fetch) 

static bool js_remoteconfig_FirebaseRemoteConfig_GetLong(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    remoteconfig::FirebaseRemoteConfig *arg1 = (remoteconfig::FirebaseRemoteConfig *) NULL ;
    char *arg2 = (char *) NULL ;
    int64_t arg3 ;
    ccstd::string temp2 ;
    int64_t result;
    
    if(argc != 2) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 2);
        return false;
    }
    arg1 = SE_THIS_OBJECT<remoteconfig::FirebaseRemoteConfig>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &temp2);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg2 = (char *) temp2.c_str(); 
    
    ok &= sevalue_to_native(args[1], &arg3, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments"); 
    result = (arg1)->GetLong((char const *)arg2,arg3);
    
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject()); 
    
    
    return true;
}
SE_BIND_FUNC(js_remoteconfig_FirebaseRemoteConfig_GetLong) 

static bool js_remoteconfig_FirebaseRemoteConfig_GetDouble(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    remoteconfig::FirebaseRemoteConfig *arg1 = (remoteconfig::FirebaseRemoteConfig *) NULL ;
    char *arg2 = (char *) NULL ;
    double arg3 ;
    ccstd::string temp2 ;
    double result;
    
    if(argc != 2) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 2);
        return false;
    }
    arg1 = SE_THIS_OBJECT<remoteconfig::FirebaseRemoteConfig>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &temp2);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg2 = (char *) temp2.c_str(); 
    
    ok &= sevalue_to_native(args[1], &arg3, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments"); 
    result = (double)(arg1)->GetDouble((char const *)arg2,arg3);
    
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject()); 
    
    
    return true;
}
SE_BIND_FUNC(js_remoteconfig_FirebaseRemoteConfig_GetDouble) 

static bool js_remoteconfig_FirebaseRemoteConfig_GetBoolean(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    remoteconfig::FirebaseRemoteConfig *arg1 = (remoteconfig::FirebaseRemoteConfig *) NULL ;
    char *arg2 = (char *) NULL ;
    bool arg3 ;
    ccstd::string temp2 ;
    bool result;
    
    if(argc != 2) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 2);
        return false;
    }
    arg1 = SE_THIS_OBJECT<remoteconfig::FirebaseRemoteConfig>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &temp2);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg2 = (char *) temp2.c_str(); 
    
    ok &= sevalue_to_native(args[1], &arg3);
    SE_PRECONDITION2(ok, false, "Error processing arguments"); 
    result = (bool)(arg1)->GetBoolean((char const *)arg2,arg3);
    
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject());
    
    
    return true;
}
SE_BIND_FUNC(js_remoteconfig_FirebaseRemoteConfig_GetBoolean) 

static bool js_remoteconfig_FirebaseRemoteConfig_GetString(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    remoteconfig::FirebaseRemoteConfig *arg1 = (remoteconfig::FirebaseRemoteConfig *) NULL ;
    char *arg2 = (char *) NULL ;
    char *arg3 = (char *) NULL ;
    ccstd::string temp2 ;
    ccstd::string temp3 ;
    char *result = 0 ;
    
    if(argc != 2) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 2);
        return false;
    }
    arg1 = SE_THIS_OBJECT<remoteconfig::FirebaseRemoteConfig>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &temp2);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg2 = (char *) temp2.c_str(); 
    
    ok &= sevalue_to_native(args[1], &temp3);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg3 = (char *) temp3.c_str(); 
    result = (char *)(arg1)->GetString((char const *)arg2,(char const *)arg3);
    
    ok &= nativevalue_to_se(result, s.rval(), nullptr /*ctx*/);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    
    
    
    return true;
}
SE_BIND_FUNC(js_remoteconfig_FirebaseRemoteConfig_GetString) 

static bool js_delete_remoteconfig_FirebaseRemoteConfig(se::State& s)
{
    return true;
}
SE_BIND_FINALIZE_FUNC(js_delete_remoteconfig_FirebaseRemoteConfig) 

bool js_register_remoteconfig_FirebaseRemoteConfig(se::Object* obj) {
    auto* cls = se::Class::create("FirebaseRemoteConfig", obj, nullptr, nullptr); 
    
    cls->defineStaticProperty("__isJSB", se::Value(true), se::PropertyAttribute::READ_ONLY | se::PropertyAttribute::DONT_ENUM | se::PropertyAttribute::DONT_DELETE);
    
    cls->defineFunction("fetch", _SE(js_remoteconfig_FirebaseRemoteConfig_fetch)); 
    cls->defineFunction("GetLong", _SE(js_remoteconfig_FirebaseRemoteConfig_GetLong)); 
    cls->defineFunction("GetDouble", _SE(js_remoteconfig_FirebaseRemoteConfig_GetDouble)); 
    cls->defineFunction("GetBoolean", _SE(js_remoteconfig_FirebaseRemoteConfig_GetBoolean)); 
    cls->defineFunction("GetString", _SE(js_remoteconfig_FirebaseRemoteConfig_GetString)); 
    
    
    
    
    cls->defineFinalizeFunction(_SE(js_delete_remoteconfig_FirebaseRemoteConfig));
    
    
    cls->install();
    JSBClassType::registerClass<remoteconfig::FirebaseRemoteConfig>(cls);
    
    __jsb_remoteconfig_FirebaseRemoteConfig_proto = cls->getProto();
    __jsb_remoteconfig_FirebaseRemoteConfig_class = cls;
    se::ScriptEngine::getInstance()->clearException();
    return true;
}




bool register_all_remoteconfig(se::Object* obj) {
    // Get the ns
    se::Value nsVal;
    if (!obj->getProperty("remoteconfig", &nsVal, true))
    {
        se::HandleObject jsobj(se::Object::createPlainObject());
        nsVal.setObject(jsobj);
        obj->setProperty("remoteconfig", nsVal);
    }
    se::Object* ns = nsVal.toObject();
    /* Register classes */
    js_register_remoteconfig_FirebaseRemoteConfig(ns); 
    
    /* Register global variables & global functions */
    
    
    
    return true;
}


#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__) || defined(__GNUG__)
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif
// clang-format on
